clc; clear; close all

l1=140.5;
l2=408;
l3=376;
l4=102.5;

syms alpha beta gamma alphad betad gammad t1 t2 t3 t4 t5 t6 td1 td2 td3 td4 td5 td6
Ezyz=[0,-sin(alpha),cos(alpha)*sin(beta);
      0,cos(alpha),sin(alpha)*sin(beta);
      1,0,cos(beta)];
  
Coef = [eye(3),zeros(3);zeros(3),simplify(inv(Ezyz))];
Coefd=diff(Coef,alpha)*alphad+diff(Coef,beta)*betad+diff(Coef,gamma)*gammad;

J = [94*cos(t1)*cos(t5) + l1*cos(t1) + l2*sin(t1)*sin(t2) + l3*cos(t2)*sin(t1)*sin(t3) + l3*cos(t3)*sin(t1)*sin(t2) + l4*cos(t2)*cos(t3)*sin(t1)*sin(t4) + l4*cos(t2)*cos(t4)*sin(t1)*sin(t3) + l4*cos(t3)*cos(t4)*sin(t1)*sin(t2) - l4*sin(t1)*sin(t2)*sin(t3)*sin(t4) - 94*cos(t2)*cos(t3)*cos(t4)*sin(t1)*sin(t5) + 94*cos(t2)*sin(t1)*sin(t3)*sin(t4)*sin(t5) + 94*cos(t3)*sin(t1)*sin(t2)*sin(t4)*sin(t5) + 94*cos(t4)*sin(t1)*sin(t2)*sin(t3)*sin(t5), -cos(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l3*cos(t2 + t3) + l2*cos(t2) + l4*cos(t2 + t3 + t4)), -cos(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l3*cos(t2 + t3) + l4*cos(t2 + t3 + t4)), -cos(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l4*cos(t2 + t3 + t4)), 94*cos(t1)*cos(t2)*cos(t3)*cos(t4)*cos(t5) - 94*sin(t1)*sin(t5) - 94*cos(t1)*cos(t2)*cos(t5)*sin(t3)*sin(t4) - 94*cos(t1)*cos(t3)*cos(t5)*sin(t2)*sin(t4) - 94*cos(t1)*cos(t4)*cos(t5)*sin(t2)*sin(t3),                                                                                                                                                                                       0
     94*cos(t5)*sin(t1) + l1*sin(t1) - l2*cos(t1)*sin(t2) - l3*cos(t1)*cos(t2)*sin(t3) - l3*cos(t1)*cos(t3)*sin(t2) - l4*cos(t1)*cos(t2)*cos(t3)*sin(t4) - l4*cos(t1)*cos(t2)*cos(t4)*sin(t3) - l4*cos(t1)*cos(t3)*cos(t4)*sin(t2) + l4*cos(t1)*sin(t2)*sin(t3)*sin(t4) + 94*cos(t1)*cos(t2)*cos(t3)*cos(t4)*sin(t5) - 94*cos(t1)*cos(t2)*sin(t3)*sin(t4)*sin(t5) - 94*cos(t1)*cos(t3)*sin(t2)*sin(t4)*sin(t5) - 94*cos(t1)*cos(t4)*sin(t2)*sin(t3)*sin(t5), -sin(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l3*cos(t2 + t3) + l2*cos(t2) + l4*cos(t2 + t3 + t4)), -sin(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l3*cos(t2 + t3) + l4*cos(t2 + t3 + t4)), -sin(t1)*(47*cos(t2 + t3 + t4 - t5) - 47*cos(t2 + t3 + t4 + t5) + l4*cos(t2 + t3 + t4)), 94*cos(t1)*sin(t5) + 94*cos(t2)*cos(t3)*cos(t4)*cos(t5)*sin(t1) - 94*cos(t2)*cos(t5)*sin(t1)*sin(t3)*sin(t4) - 94*cos(t3)*cos(t5)*sin(t1)*sin(t2)*sin(t4) - 94*cos(t4)*cos(t5)*sin(t1)*sin(t2)*sin(t3),                                                                                                                                                                                       0
                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,            47*sin(t2 + t3 + t4 + t5) - 47*sin(t2 + t3 + t4 - t5) - l3*sin(t2 + t3) - l2*sin(t2) - l4*sin(t2 + t3 + t4),            47*sin(t2 + t3 + t4 + t5) - 47*sin(t2 + t3 + t4 - t5) - l3*sin(t2 + t3) - l4*sin(t2 + t3 + t4),            47*sin(t2 + t3 + t4 + t5) - 47*sin(t2 + t3 + t4 - t5) - l4*sin(t2 + t3 + t4),                                                                                                                                                  47*sin(t2 + t3 + t4 - t5) + 47*sin(t2 + t3 + t4 + t5),                                                                                                                                                                                       0
                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                sin(t1),                                                                                                   sin(t1),                                                                                 sin(t1),                                                                                                                                                  - sin(t2 - t1 + t3 + t4)/2 - sin(t1 + t2 + t3 + t4)/2, cos(t5)*sin(t1) + cos(t1)*cos(t2)*cos(t3)*cos(t4)*sin(t5) - cos(t1)*cos(t2)*sin(t3)*sin(t4)*sin(t5) - cos(t1)*cos(t3)*sin(t2)*sin(t4)*sin(t5) - cos(t1)*cos(t4)*sin(t2)*sin(t3)*sin(t5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                               -cos(t1),                                                                                                  -cos(t1),                                                                                -cos(t1),                                                                                                                                                    cos(t1 + t2 + t3 + t4)/2 - cos(t2 - t1 + t3 + t4)/2, cos(t2)*cos(t3)*cos(t4)*sin(t1)*sin(t5) - cos(t1)*cos(t5) - cos(t2)*sin(t1)*sin(t3)*sin(t4)*sin(t5) - cos(t3)*sin(t1)*sin(t2)*sin(t4)*sin(t5) - cos(t4)*sin(t1)*sin(t2)*sin(t3)*sin(t5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                          1,                                                                                                                      0,                                                                                                         0,                                                                                       0,                                                                                                                                                                                      cos(t2 + t3 + t4),                                                                                                                                     cos(t2 + t3 + t4 - t5)/2 - cos(t2 + t3 + t4 + t5)/2];

                                                                                                                                                                                                                                                                                                                                                                                                                                                      
Jd = diff(J,t1)*td1+diff(J,t2)*td2+diff(J,td3)*td3+diff(J,t4)*td4+diff(J,td5)*td5+diff(J,t6)*td6;                                                                                    
J_inv = J^(-1);
JAnalytical = simplify(Coef * J);
JAnalytical_inv = [eye(3),zeros(3);zeros(3),Ezyz]*J_inv;
JdAnalytical = simplify(Coefd * J + Coef *Jd);


